### ISSUE TITLE
fix verification for heaters

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/ubc#184]
How can we fix the verification scripts for heaters?

See GDS files here
https://github.com/gdsfactory/ubc/actions/workflows/build_mask.yml

![image](https://user-images.githubusercontent.com/4514346/217622666-c2562da0-f331-4004-aa09-031e63df0bc9.png)

@mustafacc
@lukasc-ubc
@SkandanC

**Comment by lukasc-ubc** [comment]
Hi Joaquin,
This error has been fixed.
We are having a design review meeting right now on Zoom, if you can join.
Your layouts have some errors we should discuss.

**Comment by joamatab** [comment]
Thank you Lukas
