### ISSUE TITLE
pip install ubcpdk, fails

### ISSUE THREAD

**Issue by lukasc-ubc** [gdsfactory/ubc#333]
Hi @joamatab,

I tried to install ubcpdk but it fails:

    ERROR: Failed building wheel for gdstk

I have gdsfactory working, so perhaps this PDK has an extra dependancy that doesn't work?

thank you
Lukas

**Comment by lukasc-ubc** [comment]
I download the ubcpdk from GitHub rather than via pip.  It also doesn't work, and I get additional errors:

- file not found: config.yml
- problems with CrossSection
- @gf.cell_with_child: No module named cell_with_child

**Comment by joamatab** [comment]
Hi Lukas,

are you on python3.12?

https://github.com/heitzmann/gdstk/pull/213

**Comment by joamatab** [comment]
at the moment gdsfactory works on python3.10 and python3.11

did you also followed the instructions?
```
conda install -c conda-forge gdstk -y
pip install ubcpdk --upgrade
```

**Comment by lukasc-ubc** [comment]
I am using Python 3.10, on Mac OSX.
But I am not using conda.  I do have gdstk already installed.
gdsfactory is running correctly and I can produce layouts.  

```
lukasc@Lukass-Air gplugins % /opt/homebrew/bin/python3.10 
Python 3.10.13 (main, Aug 24 2023, 22:43:20) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdstk
>>> import gdsfactory
```

When I try to install ubcpdk, I get the following:

`lukasc@Lukass-Air gplugins % /opt/homebrew/bin/python3.10 -m pip install ubcpdk
`

```
      #include <libqhull_r/qhull_ra.h>
               ^~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      make[2]: *** [src/CMakeFiles/gdstk.dir/utils.cpp.o] Error 1
      make[1]: *** [src/CMakeFiles/gdstk.dir/all] Error 2
      make: *** [all] Error 2
      error: command '/opt/homebrew/bin/cmake' failed with exit code 2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gdstk
Failed to build gdstk
ERROR: Could not build wheels for gdstk, which is required to install pyproject.toml-based projects
lukasc@Lukass-Air gplugins % 

```

I don't get such an error with gdsfactory installation.

**Comment by joamatab** [comment]
you probably have a slightly older version of gdstk from the latest, [see](https://github.com/heitzmann/gdstk/issues/199)

i would recommend using conda

gdsfactory7 is built on top of gdstk

we are planning a major release of gdsfactory8 with klayout (no gdstk) early next year

**Comment by joamatab** [comment]
Hi Lukas,

can you try installing the ubcpdk again?

it should work now with older versions of gdstk
