### ISSUE TITLE
import_gds differend keywords

### ISSUE THREAD

**Issue by nikit-k-a** [gdsfactory/ubc#371]
In` ubcpdk/import_gds.py` in function `add_ports`:
- As from gdstk docs (https://heitzmann.github.io/gdstk/library/gdstk.Label.html) label has no `position`, should use `origin` instead maybe?
- same for `gf.Port` - there is no `midpoint` as of my knowledge. Use `center` maybe?

**Comment by joamatab** [comment]
Hi Nikita,

you are right,  thanks for pointing that out!

i also realized that the function was not used and deleted it entirely
https://github.com/gdsfactory/ubc/pull/376
