### ISSUE TITLE
samples/report sipann issues

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/ubc#58]
latest Sipann updates has some issues

![image](https://user-images.githubusercontent.com/4514346/177059810-96b7fb5d-f5b9-4d32-a788-d312e10a58af.png)

**Comment by joamatab** [comment]
https://github.com/BYUCamachoLab/SiPANN/issues/28

**Comment by SkandanC** [comment]
I have fixed the issue, and here's the result:

![image](https://user-images.githubusercontent.com/100642027/177076175-c6b3eb95-db50-411e-b73a-8323c5de20ed.png)

Opening a PR soon with my fix.

Please let me know if there are any other issues.

**Comment by joamatab** [comment]
thank you Skandan!
